development:
  adapter: postgresql
  database: criblog_db
  host: localhost
  pool: 5
  password:

test:
  adapter: postgresql
  database: criblog_db
  host: localhost

production:
  adapter: postgresql
  database: criblog_db
  host: localhost
